version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    command: ['./wait-for-it.sh', 'mysql_server:3306', '--', 'node', 'index.js']
  
  mysql_server:
    image: mysql:8.0
    volumes: 
            - ./db:/docker-entrypoint-initdb.d
    ports: 
      - 3305:3306
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=student
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    